/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ADD_H_RPCGEN
#define _ADD_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct path {
	char currentPath[1000];
};
typedef struct path path;

struct sortList {
	int listSize;
	int list[100];
	int sList[100];
};
typedef struct sortList sortList;

struct serverEcho {
	char echo[1000];
};
typedef struct serverEcho serverEcho;

struct checkFile {
	char fname[1000];
};
typedef struct checkFile checkFile;

struct matrixMultiplication {
	int row;
	int col;
	int matrix1[100];
	int matrix2[100];
	int result[100];
};
typedef struct matrixMultiplication matrixMultiplication;

#define RPC_Assignment 0x31111111
#define RPC_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define getPath 1
extern  char ** getpath_1(void *, CLIENT *);
extern  char ** getpath_1_svc(void *, struct svc_req *);
#define sort 2
extern  sortList * sort_1(sortList *, CLIENT *);
extern  sortList * sort_1_svc(sortList *, struct svc_req *);
#define printEcho 3
extern  char ** printecho_1(serverEcho *, CLIENT *);
extern  char ** printecho_1_svc(serverEcho *, struct svc_req *);
#define isFileExist 4
extern  char ** isfileexist_1(checkFile *, CLIENT *);
extern  char ** isfileexist_1_svc(checkFile *, struct svc_req *);
#define mMultiply 5
extern  matrixMultiplication * mmultiply_1(matrixMultiplication *, CLIENT *);
extern  matrixMultiplication * mmultiply_1_svc(matrixMultiplication *, struct svc_req *);
extern int rpc_assignment_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define getPath 1
extern  char ** getpath_1();
extern  char ** getpath_1_svc();
#define sort 2
extern  sortList * sort_1();
extern  sortList * sort_1_svc();
#define printEcho 3
extern  char ** printecho_1();
extern  char ** printecho_1_svc();
#define isFileExist 4
extern  char ** isfileexist_1();
extern  char ** isfileexist_1_svc();
#define mMultiply 5
extern  matrixMultiplication * mmultiply_1();
extern  matrixMultiplication * mmultiply_1_svc();
extern int rpc_assignment_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_path (XDR *, path*);
extern  bool_t xdr_sortList (XDR *, sortList*);
extern  bool_t xdr_serverEcho (XDR *, serverEcho*);
extern  bool_t xdr_checkFile (XDR *, checkFile*);
extern  bool_t xdr_matrixMultiplication (XDR *, matrixMultiplication*);

#else /* K&R C */
extern bool_t xdr_path ();
extern bool_t xdr_sortList ();
extern bool_t xdr_serverEcho ();
extern bool_t xdr_checkFile ();
extern bool_t xdr_matrixMultiplication ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ADD_H_RPCGEN */
