/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"
#include <unistd.h>
#include <stdlib.h>

/* function for reading input from user for matrix1 and matrix2 */ 
get_array(matrixMultiplication *mArray){
	
	int row, column;
	// asking user for row input
	printf("enter number of rows:");
	scanf("%d",&row);
	mArray->row = row;
	// asking user for column input
	printf("enter number of columns:");
	scanf("%d",&column);
	mArray->col = column;
	
	int i,j;
	// reading in matrix1
	printf("enter matrix 1");
	int total = 0;
		for( i=0; i<row; i++){
			for( j=0; j<column;j++){
				int value;
				printf("\nenter value for [%d], [%d] value:",i,j);
				scanf("%d",&value);
				mArray->matrix1[total] = value;
				total++;
			}	
		}
	total = 0;	
	
	// reading in matrix1
	printf("enter matrix 2");
		for( i=0; i<row; i++){
			for( j=0; j<column;j++){
				int value;
				printf("\nenter value for [%d], [%d] value:",i,j);
				scanf("%d",&value);
				mArray->matrix2[total] = value;
				total++;
			}	
		}
}

/*function to read list from user */
get_list(sortList *sList){
	int i;
	int size;
	int readValue;
	// to read list size from user
	printf("enter size of the list");
	scanf("%d",&size);
	sList->listSize = size;
	// reading in list values
	printf("enter list elements:");
	for (i=0;i<size;i++){
		scanf("%d", &readValue);
		sList->list[i] = readValue;
	}
}

void
rpc_assignment_1(char *host)
{
	CLIENT *clnt;
	char * *result_1;
	char *getpath_1_arg;
	sortList  *result_2;
	sortList  sort_1_arg;
	char * *result_3;
	serverEcho  printecho_1_arg;
	char * *result_4;
	checkFile  isfileexist_1_arg;
	matrixMultiplication  *result_5;
	matrixMultiplication  mmultiply_1_arg;
	int choice;
	char sEcho[1000];
	char flag;
	char fname[100];

#ifndef	DEBUG
	clnt = clnt_create (host, RPC_Assignment, RPC_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	do{
		/* Menu for user on client */
		printf("*******************Menu*********************\n");
		printf("1) Get Path\n");
		printf("2) Sort List\n");
		printf("3) Echo\n");
		printf("4) Check file \n");
		printf("5) Matrix Multiplication\n");
		printf("6) Exit\n");
		printf("Enter your choice:\n");
		scanf("%d",&choice);
		switch(choice){
				// if user choice is 1 then getpath function is called
				case 1:
					result_1 = getpath_1((void*)&getpath_1_arg, clnt);
					if (result_1 == (char **) NULL) {
						clnt_perror (clnt, "call failed");
					}else{
						printf("current working path is : %s \n", *result_1);	
					}
					break;	

				// if user choice is 2 then sort function is called
				case 2:	
					// get_list function is used to read in list values from user
					get_list(&sort_1_arg);
					result_2 = sort_1(&sort_1_arg, clnt);
					if (result_2 == (sortList *) NULL) {
						clnt_perror (clnt, "call failed");
					}else{
						int i=0;
						int size = result_2->listSize;
						printf("printing sorted array: \n");
						for (i=0;i<size;i++){
							printf("%d\n", result_2->sortedList[i]);
						}
					}
					break;
					
				// if user choice is 3 then printecho function is called	
				case 3:	
					// takes in string input from user
					printf("Enter something to echo on server:\n");
					scanf("%s",&sEcho);
					strcpy(printecho_1_arg.echo,sEcho);
					result_3 = printecho_1(&printecho_1_arg, clnt);
					if (result_3 == (char **) NULL) {
						clnt_perror (clnt, "call failed");
					}else{
						printf(" Echo from server : %s \n", *result_3);
					}
					break;
				
				// if user choice is 4 then isfileexist function is called				
				case 4:	
					// reads file name thats needs to be searched
					printf("Enter file that you want to look up:\n");
					scanf("%s",&fname);
					strcpy(isfileexist_1_arg.fname,fname);
					result_4 = isfileexist_1(&isfileexist_1_arg, clnt);
					if (result_4 == (char **) NULL) {
						clnt_perror (clnt, "call failed");
					}else{
						printf("%s \n", *result_4);
					}
					break;
					
				// if user choice is 5 then mmultiply function is called	
				case 5:
					//get_array function is used to read in matrices from the user
					get_array(&mmultiply_1_arg);
					result_5 = mmultiply_1(&mmultiply_1_arg, clnt);
					if (result_5 == (matrixMultiplication *) NULL) {
						clnt_perror (clnt, "call failed");
					}else{
						int i,j;
						int row = result_5->row;
						int col = result_5->col;
						printf("result matrix is:\n");
						printf("[\n");
						// printing the result which was returned server
						for(i=0; i<row; i++){
							for(j=0; j<col; j++){
								printf("%d,", result_5->resultMatrix[i*col+j]);
							}
								printf("\n");
						}
						printf("]\n");
					}
					break;
				
				// if user choice is 6 then program terminates
				case 6:
					exit(0);
					break;
				}		
		}while(1);	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	rpc_assignment_1 (host);
exit (0);
}
